### PR TITLE
Adding OpenDSA interactive eTextbook

### PR DESCRIPTION
**Pull request by hamzakat**
OpenDSA is an OSS project which offers an interactive web-based data structure and algorithms eTextbook
https://github.com/OpenDSA/OpenDSA/

I think it is a great DSA textbook which I used to read while studying the data structure course in the university. It is rich with animated examples which gives a great studying experience (almost every algorithm and data structure is animated and can be adjusted by the reader). 
I think it can be listed, as a DSA reference.

### CODE REVIEW

**Comment by waciumawanjohi** [comment]
An interesting project! I certainly like the fact that it is an open source project.

The proposed link is to the 'everything' course, which includes a fair bit of content that is not about data-structures (e.g. Debugging in Eclipse, Pointers in Java, etc). Perhaps there is a version of the book that is more focused?

**Comment by aayushsinha0706** [comment]
Are we looking for this link (Open DSA textbook)[https://opendsa-server.cs.vt.edu/OpenDSA/Books/Everything/html/index.html]

**Comment by hamzakat** [comment]
@waciumawanjohi 
Here you can find all distributions
https://opendsa-server.cs.vt.edu/home/books

**Comment by waciumawanjohi** [comment]
@hamzakat Great! Is there one that is a better fit for the Readings than the "Everything" book?

**Comment by hamzakat** [comment]
@waciumawanjohi 

Well, here is what I found:
- [CS2 Software Design & Data Structures](https://opendsa-server.cs.vt.edu/OpenDSA/Books/CS2/html/#)
- [CS3 Data Structures & Algorithms](https://opendsa-server.cs.vt.edu/OpenDSA/Books/CS3/html/#)
    - [CS3 Coursenotes](https://opendsa-server.cs.vt.edu/OpenDSA/Books/CS3notes/html/) 
    - [Presentation slides for "CS3" course on Data Structures.](https://opendsa-server.cs.vt.edu/OpenDSA/Books/CS3slides/html/)
- [Senior Algorithms](https://opendsa-server.cs.vt.edu/OpenDSA/Books/CS4104/html/#)

And "Everything" book combines all of the books above into one book or reference. Also, they mentioned that CS3 book is " A post-CS2-level course", knowing that there are some common sections between CS2 and CS3. However, I think that CS3 book is a good one to add regarding DSA subjects, whereas the "Senior Algorithms" book is more focused on Algorithm Analysis subjects.

**Comment by waciumawanjohi** [comment]
Good background info!

You're making a proposal to add a version to Readings. The initial PR referenced the Everything book. I think that's too broad and includes material that shouldn't be recommended. You point out the difference between two versions; which is best suited for Readings? Or is there a way to make a combined version that's even better tailored than those two options?

**Comment by hamzakat** [comment]
Hey @waciumawanjohi 
Thanks for responding.
I tried to declare the difference between the textbooks' subjects. I said I prefer to add CS3 book in my previous comment because I intended to add a book about DSA when I made the PR, and I wasn't aware of all of these copies. 
Anyway, we can instead add all of the OpenDSA textbook copies in the same organization I structured in my previous comment.

**Comment by hamzakat** [comment]
@waciumawanjohi 
You can review the changes

**Pull request closed without merging**
