### PR TITLE
alternative link for Computation Structures 1: Digital Circuits

### PR DESCRIPTION
**Pull request by githubusar**
[Computation Structures 1: Digital Circuits](https://learning.edx.org/course/course-v1:MITx+6.004.1x_3+3T2016) is not available on edx so this is an alternative link:

https://computationstructures.org/lectures/info/info.html

Screenshot 2022-04-22 at 14 06 43

### CODE REVIEW

**Comment by InvisibleX90** [comment]
@githubusar learning.edx.org link is working completely fine. If you can't see anything try logging in again.

**Comment by githubusar** [comment]
@[InvisibleX90](https://github.com/InvisibleX90) try to enroll [Computation Structures 1: Digital Circuits](https://learning.edx.org/course/course-v1:MITx+6.004.1x_3+3T2016) the link will not enroll you in the course.

Screenshot 2022-04-22 at 22 11 39

**Comment by spamegg1** [comment]
It is also working for me, I was able to enroll in all 3 courses. edX is so damn inconsistent these days. I think it's fine to add the alternative link.

**Comment by waciumawanjohi** [comment]
1. This pull request was malformed, pointing from master to an unrelated feature branch. Github has closed the PR because the feature branch was merged to master and deleted.

2. The discussion above is about a non-substantive change. Feel free to create a pull request to add the links identified by spamegg as alternate links for the computational structures courses.

**Pull request closed without merging**
