### PR TITLE
Enable Markdown detection.

### PR DESCRIPTION
**Pull request by MichaelHinrichs**

### CODE REVIEW

**Comment by waciumawanjohi** [comment]
Please provide a description/explanation on pull requests.

**Comment by waciumawanjohi** [comment]
It's not clear to me why it's helpful. Explain from the point of view of the average (or even 95th percentile) visitor how this change will improve their experience.

**Comment by MichaelHinrichs** [comment]
In a normal repo, you wouldn't use this because the markdown is just documentation for the main content. In a document repo, like this one, it IS the main content. Repos like this are what these settings exist for in the first place. People will search for doc repos with `language:markdown` and this would not show up. It's a search engine optimization.

**Comment by waciumawanjohi** [comment]
Ok, pardon me for being a bit obtuse. Help me understand the user perspective on this improvement. You stated "People will search for doc repos with language:markdown and this would not show up." Give me a hypothetical user that we want to empower. What are they doing that the absence of this tag inhibits? (My mental model for our users is, "I'm searching the internet for a recommendation on how to learn computer science" and we want them to be able to find OSSU and our recommended courses)

**Comment by MichaelHinrichs** [comment]
Ugh! Forget it.

**Comment by muzimuzhi** [comment]
Tip: `language:markdown` can already find the `.md` files in this repo, see https://github.com/search?q=repo%3Aossu%2Fcomputer-science+language%3AMarkdown+&type=code

**Pull request closed without merging**
