### PR TITLE
Code of conduct

### PR DESCRIPTION
**Pull request by sTiKyt**
Simple social code of conduct.

### CODE REVIEW

**Comment by thesohelshaikh** [comment]
I feel it should be left as is. OSSU offers several career paths and it would be better to point all of them to the same repo rather than having a separate code of conduct for each path.

**Comment by vapeurs** [comment]
@thesohelshaikh 

I am not sure he is aware there already exists a code of conduct: https://github.com/ossu/code-of-conduct

**Comment by vapeurs** [comment]
They almost look identical, apart from some glaring differences.

**Comment by vapeurs** [comment]
asa

**Comment by hanjiexi** [comment]
Hi @sTiKyt I am closing this pull request on your behalf; as others mentioned above, we use a centralized code of conduct for all of OSSU. Thanks for your enthusiasm to contribute!

**Pull request closed without merging**
