### PR TITLE
add IR book by stanford/nlp

### PR DESCRIPTION
**Pull request by seralf**
added the book "An Introduction to Information Retrieval", available on the nlp.stanford site

### CODE REVIEW

**Comment by ixAp0c** [comment]
Pull Request?

Patch? 442 I got the patch

On Fri, Dec 29, 2017 at 10:05 AM, Alfredo Serafini <notifications@github.com

**Comment by seralf** [comment]
I added a reference from the web interface, maybe it created a path instead
of a proper PR

2017-12-29 17:58 GMT+01:00 Robb C. <notifications@github.com>:

**Comment by hanjiexi** [comment]
This book looks great! Thanks for PR. I'm merging it into the `dev` branch, which is our staging area before making an update to `master`.

**Comment by seralf** [comment]
thanks!

2017-12-30 19:02 GMT+01:00 hanjiexi <notifications@github.com>:

**Pull request merged**
