### PR TITLE
Update PROJECTS.md

### PR DESCRIPTION
**Pull request by muhtalhakhan**
Added CS Algorithms -> Programming

### CODE REVIEW

**Comment by waciumawanjohi** [comment]
This appears to be someone else's work. Projects should be your own work.

**Comment by muhtalhakhan** [comment]
Nope, these are the projects which can help everyone.

I hope you understand my point and I never claimed that those projects are mine.

Thank you!!

**Comment by muhtalhakhan** [comment]
@waciumawanjohi btw May I get to know why people are contributing to OSSU?

**Comment by waciumawanjohi** [comment]
For many of the same reasons people contribute to other worthy projects. If you'd like to hear from OSSU participants, I recommend joining the discord!

**Comment by waciumawanjohi** [comment]
> Nope, these are the projects which can help everyone.
> 
> I hope you understand my point and I never claimed that those projects are mine.
> 
> Thank you!!

Ah, that's not the purpose of Projects.md. This page is meant as a showcase of student work. The document specifies:
> Here, we are providing a list of projects done by the community for the final projects. You may use these as inspirations for your own final project! Projects created by OSSU's students for each course of our [Computer Science](https://github.com/ossu/computer-science) curriculum.

Glad to hear that you are interested in OSSU. If you would like to contribute and improve OSSU the [contributing guide](https://github.com/ossu/computer-science/blob/master/CONTRIBUTING.md) names a number of ways to do so. And the [discord community](https://discord.gg/wuytwK5s9h) is a place where you can discuss more with other OSSUnians.

**Pull request closed without merging**
