### PR TITLE
Add Pre-Calculus courses before Core Math courses

### PR DESCRIPTION
**Pull request by danmoop**
Actually there should be Pre-Calculus because I haven't found them on the list. I list they are really important and should be on the list. All the courses are on Coursera.org as other courses from "Core Math"

### CODE REVIEW

**Comment by chinguelessi** [comment]
I agree with this. Actually, I already planned to make Pre-Calculus before the Core Math in my adapted curriculum. However, maybe others don't need to take it because they already mastered it in school.

**Comment by danmoop** [comment]
I want this to be added because I study at school at 10 form and haven't mastered Pre-Calculus yet.

**Comment by hanjiexi** [comment]
We're trying to keep the core curriculum limited to college-level material so that the curriculum size doesn't grow out of control. If we are going to start adding pre-requisites that are (generally) pre-college level, then we should probably have a separate section for that.

**Comment by smurfMT** [comment]
Maybe it's an idea to add it as a reference link or remove it as required from core maths, as I last went to high school over 10 years ago, and do need something like this to refresh...

**Comment by hanjiexi** [comment]
We can give some better guidance on where to fulfill prerequisites under
the "Prerequisites" section, but I had assumed Khan Academy offers the best
high-school level resources for these subjects. Has anyone taken the
Coursera courses that were suggested in this pull request? How do they
compare to Khan Academy's coverage?

**Comment by Nixerrr** [comment]
I've been doing this course ([Arizona State University: MAT170 - Precalculus)](https://courses.edx.org/courses/course-v1:ASUx+MAT170x+2T2017/course/) in parallel with Khan Academy, and while Khan Academy is better at providing theory and explanations, this course is great at drilling and practicing those concepts.

**Comment by shailalias** [comment]
I strongly agree with @Nixerrr . The ASU course is a fantastic refresher. It has you do a pretest before starting the course, so you only need to spend time on topics you are unsure of. As they mentioned, it also has a great review method for each section.

**Comment by spelga** [comment]
I've been using ASU as well as I find Khan Academy very slow to progress
through. If I get stuck on something I then check out the KA section on it.
Otherwise ASU much quicker to get you up to speed. There's also a High
School version if jumping straight into Precalc seems too high an initial
hurdle if you have been away from maths for many years and really rusty.

**Comment by hanjiexi** [comment]
Closing this PR, please continue the discussion in #438. Thanks!

**Pull request closed without merging**
