### PR TITLE
Add Calculus, Discrete Mathematics and Its Applications & The Art of Computer Programming to optional readings.

### PR DESCRIPTION
**Pull request by DionGR**
The 2 Core Math books are academic must-reads for upcoming Computer Scientists. 
The Art of Computer Programming is referenced in a lot of top notch courses (such as Sedgewick's Algorithms) and is generally a great series of books to read at some point in your career.

**Books Added:**

Core Math:

- Calculus - Michael Spivak

- Discrete Mathematics and Its Applications - Kenneth Rosen

Core Theory:
- The Art of Computer Programming - Donald Knuth

### CODE REVIEW

**Comment by bradleygrant** [comment]
> The 2 Core Math books are academic must-reads for upcoming Computer Scientists.

According to who? Do you have a source?

Spivak's Calculus is a course in real (function) analysis; while this will help (or almost singlehandedly ensure) mathematical maturity, I see nothing in CS2013 which would make this required reading for undergraduate computer scientists. In fact I would reason we want to *discourage* excursions into pure math as much as possible.

Rosen's Discrete Math is used as a discrete math textbook in many universities, but these are covered sufficiently well in 6.042J -- I don't see a compelling reason to add this as anything but supplementary material.

The addition of Knuth makes sense and could be appropriate as an optional reading.

**Comment by bradleygrant** [comment]
That said, Spivak might make sense for the https://github.com/ossu/math curriculum. We have a couple of candidate courses for the A-Calc/Intro Analysis course but no clear winners as of yet.

**Comment by DionGR** [comment]
> > The 2 Core Math books are academic must-reads for upcoming Computer Scientists.
> 
> According to who? Do you have a source?
> 
> Spivak's Calculus is a course in real (function) analysis; while this will help (or almost singlehandedly ensure) mathematical maturity, I see nothing in CS2013 which would make this required reading for undergraduate computer scientists. In fact I would reason we want to _discourage_ excursions into pure math as much as possible.
> 
> Rosen's Discrete Math is used as a discrete math textbook in many universities, but these are covered sufficiently well in 6.042J -- I don't see a compelling reason to add this as anything but supplementary material.
> 
> The addition of Knuth makes sense and could be appropriate as an optional reading.

The category is called Great Readings. All of the aforementioned books are, indeed, Great Readings for CS undergrads/grads!

CS is, in its core, a Math-derived Science. Therefore a heavy theoretical book like Spivak's Calculus is, indeed, a Great Reading for people who want to dive deeper into Math.

Rosen's Discrete Math is one of the most acclaimed Discrete Math books out there. Just because it's "covered sufficiently", it does not mean it should not be included in the category Great Readings as supplementary material!

**Comment by saerosV** [comment]
One problem that I think could start affecting the Great Readings file, due to the great number of new books added, is disorganization. 

Should the file have its sections (i.e., Systems, Math) further divided into subsections (i.e., Calculus, Operating Systems)?

**Comment by DionGR** [comment]
> One problem that I think could start affecting the Great Readings file, due to the great number of new books added, is disorganization.
> 
> Should the file have its sections (i.e., Systems, Math) further divided into subsections (i.e., Calculus, Operating Systems)?

I agree that the Great Readings section could be MUCH more organized.

**Pull request closed without merging**
