### PR TITLE
Removed Project with Dead Link

### PR DESCRIPTION
**Pull request by kyedavey**
1. Removed Binary Machine project as repository link results is dead.
2. Fixed link to applications block.

### CODE REVIEW

**Comment by waciumawanjohi** [comment]
1. Makes sense
2. I cannot see what change has been made here.

**Comment by kyedavey** [comment]
2. The link on line 13 is currently #applications, the section title is application (non plural). Have just dropped the s on line 13 to correctly link to the application section of this document.

**Comment by waciumawanjohi** [comment]
Ah, makes sense. What is the change to line 42?

**Comment by kyedavey** [comment]
No edits where made on line 42, this is just a whitespace change

**Comment by waciumawanjohi** [comment]
Sounds good. Thanks for the sharp eye!

**Pull request merged**
