### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by anantav51**
[Inaccurate course duration](https://www.edx.org/course/introduction-to-probability)

### CODE REVIEW

**Comment by waciumawanjohi** [comment]
There are changes in this PR that are unrelated. Some are non-substantive changes that don't require an RFC. Others are substantive and went through the RFC process. These should be separate PRs.

Let me know if you'd like help opening two separate PRs. It only involves having two different branches in your repo, each of which has their own changes and opening a PR for both branches.

**Comment by anantav51** [comment]
> There are changes in this PR that are unrelated. Some are non-substantive changes that don't require an RFC. Others are substantive and went through the RFC process. These should be separate PRs.
> 
> Let me know if you'd like help opening two separate PRs. It only involves having two different branches in your repo, each of which has their own changes and opening a PR for both branches.

Thank you for bringing this to my attention. I apologize for not separating the changes correctly. I will undo the changes and mark it ready for review.

**Comment by waciumawanjohi** [comment]
From Stat 110 page:

> The edX course focuses on animations, interactive features, readings, and problem-solving, and is complementary to the Stat 110 lecture videos on YouTube, which are available at https://goo.gl/i7njSb

It sounds as if the course site has additional material that could justify a longer timeline than the edX course alone.

**Comment by anantav51** [comment]
> From Stat 110 page:
> 
> > The edX course focuses on animations, interactive features, readings, and problem-solving, and is complementary to the Stat 110 lecture videos on YouTube, which are available at https://goo.gl/i7njSb
> 
> It sounds as if the course site has additional material that could justify a longer timeline than the edX course alone.

Thanks for pointing it out. However, I believe the total time needed to finish the course is still less than 288 hours. The total length of the playlist is [approximately 30 hours](https://i.imgur.com/Ji58P0T.png), and when factoring in the time needed to internalize and process the videos, it could take an additional 50 hours to finish the playlist. In combination with the 100-hour edX course (which is the upper bound), this would bring the total course time to around 150 hours, or 15 weeks with a consistent effort of 10 hours per week.

**Comment by waciumawanjohi** [comment]
Merging this in. I will be interested to hear from future students if they believe the new time estimate is accurate. (The larger the sample size, the more confident one can be that a measurement is accurate)

**Pull request merged**
