### PR TITLE
Added Tools section on extra/courses

### PR DESCRIPTION
**Pull request by agonxgashi**
Added two new courses ( "Version Control with Git" & "How to Use Git and GitHub" ) to extra/courses.md because I belive that every student that wants to learn about Open-Source Softwares, should know one thing or two about Git and to be able to easily work with it.

### CODE REVIEW

**Comment by lmsonic** [comment]
The link on the second course doesn't work, it starts with hhttp instead of http

**Comment by agonxgashi** [comment]
@lmsonic yes, there are two commits on this PR. I fixed that typo on the second one.

**Comment by aryzach** [comment]
@agonxgashi was this removed? I can only find the course through this conversation, but not on the extras page

**Comment by Alaharon123** [comment]
Seeing as this pull request is still open, I'd assume it hasn't been added. Probably because it's two commits instead of one.

**Comment by aryzach** [comment]
@Alaharon123 so clearly I should take this class because I didn't know 'open' means it wasn't added haha

**Comment by waciumawanjohi** [comment]
Thumbs up on the `How to Use Git and Github` course. See here: https://github.com/ossu/computer-science/issues/421

It's not clear that we need two courses on git. But I think the fact that this pull request exists tells us that putting the Git resources on the Contributing page is not sufficient. Merging and modifying this.

**Pull request merged**
