### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ironroggers**
Grammatical Changes and converted Normal to Italics (line 164), improved readablity

### CODE REVIEW

**Comment by micahbales** [comment]
This is new to me. Apparently GitHub spam is a thing?

**Comment by micahbales** [comment]
This may be related to Hacktoberfest, and they give instructions on how to mark these PRs as spam so that they are not rewarded. https://hacktoberfest.digitalocean.com/details#spam

**Comment by waciumawanjohi** [comment]
Thanks @micahbales !

**Comment by ironroggers** [comment]
I was learning something new but bad to hear if they(hacktoberfest) do so.
But I suggested some minimal changes, they might be good, might not be.

**Comment by waciumawanjohi** [comment]
@ironroggers OSSU is a community supported project. We welcome contributors who put in the hours to make the curriculum better for all students. That said, one of the four changes you proposed here was to change one exclamation point to three exclamation points. That's not adding the sort of value that our students need.

I encourage you to read the contributing guidelines in OSSU:CS. It will help you to write Issues in the future so that you can say with gusto, "This change IS good."

https://github.com/ossu/computer-science/blob/master/CONTRIBUTING.md

_I am unsubscribing from this closed PR and won't receive any notifications of future messages_

**Comment by ironroggers** [comment]
I respect your denial to my pull request, actually I am new to GitHub. But
now that I know the issues I will work on it to the best of my ability.

**Pull request closed without merging**
