### PR TITLE
Clarify OSTEP Options

### PR DESCRIPTION
**Pull request by waciumawanjohi**
Direct most students to read OSTEP and complete homework.
Direct only students specializing in systems to undertake
the course projects

Resolves [#1083](https://github.com/ossu/computer-science/issues/1083)

Co-authored-by: Waciuma Wanjohi <code@waciuma.com>
Co-authored-by: spamegg <spamegg@pm.me>

### CODE REVIEW

**Comment by waciumawanjohi** [comment]
@spamegg1 Here's the promised edit of your draft. If you reply and give this the go-ahead, I'll merge it in. If there are changes you'd like to make, just make a PR to the OSTEP-Approaches branch.

**Comment by spamegg1** [comment]
@waciumawanjohi I looked over it, looks good to merge :+1:

**Comment by riceeatingmachine** [comment]
In the document:

"There is a great solution set here."

Link is missing.

**Comment by riceeatingmachine** [comment]
The pre-requisites on the main page says "strong C programming".

It should be changed to "none" then I presume? Assuming the "base" approach is the default?

**Comment by spamegg1** [comment]
@riceeatingmachine Good catch, it's my bad I missed that missing link. I'll fix it.

The prerequisites should not be changed to "none" because that leads to people skipping the entire curriculum and jumping into that course by saying "it had no prerequisites, so I just started it", then getting horribly stuck not knowing what to do. (Same happens with Nand2Tetris). Whether the basic or extended approach is taken, Nand2Tetris Part II is a good prerequisite (makes you write a basic "OS" in the last project).

**Pull request merged**
