### PR TITLE
Added link to Facebook group

### PR DESCRIPTION
**Pull request by thesohelshaikh**
Group created by @vapeurs.

Link to group: https://www.facebook.com/groups/670159103342710/

### CODE REVIEW

**Comment by hanjiexi** [comment]
We used to have a Facebook here: https://www.facebook.com/ossuniversity

But it was removed by Eric to consolidate our social media presence. Social media is quite foreign to me — yes, I know how strange that sounds! — so I'm not really sure what's best to do here.

**Comment by thesohelshaikh** [comment]
I understand it makes the community separated but giving an option to communicate is necessary. A lot of new articles are being published and other resources which do not fit in the curriculum can be posted here to keep the community going. 

Either way, if you feel differently, you may go ahead and close the pull request.

**Comment by waciumawanjohi** [comment]
I think that Eric was right to consolidate OSSU's social media presence. The gitter is an open platform that still has plenty of capacity. Prior to the consolidation, OSSU communication channels were sparse with little interaction.

**Comment by hanjiexi** [comment]
I'm going to go ahead and close this. I have no problem that people create their own private interest groups on whatever platforms they're using, but my impression is that the most successful technical communities consolidate around three basic communication channels: a single chat room (often via Discord, Gitter, or Slack), a single forum (usually Discourse), and GitHub/GitLab issues for specific problems with specific repositories.

**Pull request closed without merging**
