### PR TITLE
fix time estimation for PLA

### PR DESCRIPTION
**Pull request by romanbird**
The estimation for PLA are taken directly from coursera but are a significant underestimation. (my theory is that its not taking into account the time to do the problem sets).

### CODE REVIEW

**Comment by waciumawanjohi** [comment]
I'm certainly aware that folks can make a mistake or a bad estimate. At the same time, declaring that the instructor/platform time and effort estimates are wrong will need more than one student's experience. Happy to leave this PR in place so that other students can chime in. The discord channel for the courses would be a good place to recruit students to share their experience. A simple google poll could make the gathering and analyzing the data much simpler.

**Comment by waciumawanjohi** [comment]
I'll also say, it seems in the platform's interest to have accurate time/effort analyses. I would be interested what Coursera would say regarding how estimates are calculated and if this one should be increased. The professor, Dan Grossman, has a webpage where he shares his contact information, he may also be willing to talk about how the current estimate was made and whether it has been borne out by experience.

**Comment by romanbird** [comment]
The instructor says all three parts should take 100 or more hours in the intro lecture video which more or less aligns with this adjustment.

**Comment by riceeatingmachine** [comment]
The projects at the end of each week took me 6-12 hours each. The 4-8h estimate is incorrect. 

The 8 to 12h is a better assessment, but for me it was closer to 15 hours per week, if not more.

The videos are about 4 hours. The reading takes 1-2 hours. The projects takes 8-9 hours on average. The peer reviews take an additional hour. 

I would say it would be better to list 12-16 hours per week. Also the first course is only 4 weeks long. The first week is just a quick intro.

**Pull request closed without merging**
