### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Elias-Dickinson**
Per the instructor of How to Code - Simple Data, the course is based on the second edition.

### CODE REVIEW

**Comment by ShaoxuanYin** [comment]
cool

**Comment by Alaharon123** [comment]
Shouldn't we just link to the site's main page and have people click to get the latest version of the textbook?

**Comment by waciumawanjohi** [comment]
The First edition is linked because at the time of writing the second edition did _not_ provide solutions to the problems. Has that changed?

**Comment by Elias-Dickinson** [comment]
> The First edition is linked because at the time of writing the second edition did _not_ provide solutions to the problems. Has that changed?

It does not. Given that’s the entire point of using the older book, should I just close the pull?

**Comment by waciumawanjohi** [comment]
Yeah, I think that's the best option. At some point we'll come up with a format that is a little richer and can give more context to each course. At that time we should be able to point out the differences between first and second edition and let students choose. Given space to recommend just one, I lean to the option that gives students feedback.

**Comment by Elias-Dickinson** [comment]
After getting feedback I am going to withdraw the pull request

**Comment by Alaharon123** [comment]
Maybe the link should be changed so it's linking from the words "the first edition"?

**Pull request closed without merging**
