### PR TITLE
Add programming language as requirement for Nand To Tetris Part II

### PR DESCRIPTION
**Pull request by leungleoqin**
One of these two programming languages are required to complete the course assignments, most of which ask students to write programs to parse/compile the Jack language into VM code, or translate VM code into machine language.

The requirement is stated in the video lecture "[Week 1 > Course Overview > Course Overview (20 min)](https://www.coursera.org/learn/nand2tetris2/lecture/jEmbG/course-overview)" at 17:06:

"We expect that you have some programming ability, st the level which is acquired in typical Introduction to Computer Science courses. **So you have to know either Java or Python**. You have to know the basic techniques and skills of object-oriented programming. If you have this basic knowledge, then you're welcome to take Nand to Tetris Part II. It is also recommended, but certainly not required, that you will take Nand to Tetris Part I. In fact, the two courses are so independent of each other that you can take them in reverse order, if you will. But of course we recommend that you take part one first, part two second. But once again, you don't have to. You can start from scratch with the Nand to Tetris Part II."

### CODE REVIEW

**Comment by a1h05** [comment]
image
In the second part of the course they explicitly list supported languages. In my opinion it would be better just to write "any programming language".

**Comment by leungleoqin** [comment]
@a1h05 is that from the course assignment page? I did not pay for the certificate and I couldn't find that list anywhere else.

**Comment by a1h05** [comment]
@leungleoqin yes, it is from the assignment page.
In the lectures they do not force to use any particular language. They just propose general structure of solution, I believe they mentioned Java and Python more as example.

**Comment by leungleoqin** [comment]
@a1h05 Cool, I have updated it to say "any programming language"

**Comment by hanjiexi** [comment]
Fixing this has been on my backlog for a while, so thanks for taking the lead!

The ideal fix would allow us to link to the official list of supported programming languages. Unfortunately this doesn't work. So the second-most ideal fix, in my opinion, is to maintain our own public version of this list and update it whenever the official list changes, and then link to that list under the prerequisites.

For a quick fix that doesn't involve creating new files, you could link to [this image](https://user-images.githubusercontent.com/2046800/35426340-f6ce6358-026a-11e8-8bbb-4e95ac36b1d7.png).

**Comment by hanjiexi** [comment]
Also, @leungleoqin, are you able to rebase your commits on the `dev` branch instead of `master`? We use `master` only for new stable releases.

Sorry for the extra work. I have just changed the default branch of the repository to `dev` so that future PRs will default to it.

**Comment by leungleoqin** [comment]
@hanjiexi My bad. I have updated the Readme to include the link, and rebased to the dev branch. You might want to keep the default branch as master though, since users will now see the dev branch by default if they go to the repo page.

**Comment by hanjiexi** [comment]
> You might want to keep the default branch as master though, since users will now see the dev branch by default if they go to the repo page.

It's definitely a trade-off, but one I am willing to make because in the future we will likely have a different homepage (apart from just the repository page) that draws its content from the master branch.

**Pull request merged**
