### PR TITLE
Update Hours and Weeks for programming language courses (and weeks for calculus 1C)

### PR DESCRIPTION
**Pull request by riceeatingmachine**
Fixed the weeks and hours for programming languages courses and part 3 of calculus course

Switched the prerequisite for Software Engineering: Introduction from Software Construction to NAND2Tetris

### CODE REVIEW

**Comment by waciumawanjohi** [comment]
There are 2 different things in this pull request:
- Changing the prerequisite for Software Construction: aryzach has been iterating on a pull request to address this over this week. Those changes have been merged in. You can see that here: https://github.com/ossu/computer-science/pull/711
- Changing the time estimates for courses. Can you help me understand how you arrived at the new time estimates?

**Comment by riceeatingmachine** [comment]
You can see the hourly commitment under each course for the programming languages on their page, for example, for Part A

https://www.coursera.org/learn/programming-languages#syllabus

Week 1 - 4 hours
Week 2 - 6 hours
Week 3 - 7 hours
Week 4 - 8 hours
Week 5 - 5 hours

Coursera (as far as I understand) comes up with these times by averaging the time taken by it's users to complete the courses.

**Comment by waciumawanjohi** [comment]
Yup, that makes sense! Thanks for catching those. If you rebase the pull request on the current state of master and remove the changes to Software Construction, I'll merge that in.

**Comment by riceeatingmachine** [comment]
I have removed the #711 portion of the pull request, leaving only the hours and weeks changed.

**Comment by waciumawanjohi** [comment]
Did you rebase the branch from master? Github is stating there are conflicts that cannot be resolved.

Git's documentation on rebasing is pretty good: https://git-scm.com/book/en/v2/Git-Branching-Rebasing

**Comment by riceeatingmachine** [comment]
Screenshot from 2020-05-10 22-48-24

I see no conflicts!

**Comment by riceeatingmachine** [comment]
Okay, I made the same changes to FAQ.md 

It should work now!

**Comment by waciumawanjohi** [comment]
Screen Shot 2020-05-10 at 1 04 56 PM

I'm not sure why Github is showing a green path to one of us and a conflict message to another.

That said, I think that you've copied the changes that aryzach made into additional changes on your branch. That won't be sufficient to fix the problem. The issue is that you are saying to git, I want to add my commits after commit X. And git is objecting that the current state is commit X+1. Creating additional commits that you want to add on to commit X will not resolve that conflict. Instead, you need to rebase your branch from the current state of master. Then the merge command will tell git, I want to add commits after commit X+1.

**Comment by riceeatingmachine** [comment]
I'll make a new pull request tomorrow morning.

Alternatively, can you unmerge aryzach and merge me in?

**Comment by riceeatingmachine** [comment]
See #712

**Pull request closed without merging**
