### PR TITLE
Changed Software Engineering: Introduction prereqs

### PR DESCRIPTION
**Pull request by aryzach**
We removed the Software Construction classes, so I changed the prereq for this class

### CODE REVIEW

**Comment by waciumawanjohi** [comment]
Hmmm... I agree that we should remove the reference to Software Construction. I wonder if instead of stating Programming Languages Part C is a pre-req, we should say Core Programming. Is there anything in particular about the Programmin Language progression that this course relies upon?

**Comment by aryzach** [comment]
Yeah I agree with you. That's kinda what I meant just because Part C requires Part B then Part A, but Part A doesn't require HtC. Changing it to Core Programming makes more sense.

I haven't taken the Software Engineering course btw, just saw that the prereq was outdated. That said I also think nand2tetris part 2 might be a good prereq, because it's the largest program created up to this point in the curriculum (havent taken OS 3 easy pieces yet, so barring that). I think having some context of working with large programs gives some context to something like a SE course, because SE is trying to solve the problem of dealing with large programs / code bases. Prior to going through the struggle of building the compiler and VM translator in nand2tetris, I don't think I would have as much context to understand the benefits of SE. It presented a lot of pain points that would probably be helped with some SE ideas. But, that large project prereq that I'm suggesting definitely doesn't have to come from nand2tetris.

**Comment by waciumawanjohi** [comment]
You've made a compelling argument for Nand2Tetris. That makes a lot of sense. Can you alter the pull request to reflect that? I'll merge it in!

**Comment by aryzach** [comment]
hey @waciumawanjohi I'm not too familiar with pull requests. The second one (3e719e0) is the correct one (had a typo). Let me know if there's anything else I need to do to get this merged

**Comment by waciumawanjohi** [comment]
I looked at the commit. It looks like it still recommends Programming Languages Part C, rather than the more generalized Core Programming. I'm still concerned that this increased specificity is a bit of misdirection.

On altering pull requests, you may want to look into how to "squash" commits. This is something that I often do when I'm working on a feature branch of a project. When I begin to work on some new feature, I check out a new branch of the repo. As I work, I make commits to my branch. When I finish, I rebase the branch from the master branch. Then I'll do an interactive rebase to shrink the number of my commits that will be merged in to master.

That short explanation may be more confusing than illustrative. Here's a much longer article about rebasing, etc. https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history

**Comment by aryzach** [comment]
@waciumawanjohi please ignore this thread and SHA d40aa34. I had some trouble with the rebase, so I just made a fresh copy of the repo and re-made my changes (obviously still a rookie!)

There's a fresh pull request that should be good to go (#711 with SHA dca6aa3) Here: https://github.com/ossu/computer-science/pull/711/commits/dca6aa33c69d0e09406de96131c28cdaaeec3640

**Pull request closed without merging**
