### PR TITLE
Add "Practical C Programming by Steve Oualline"

### PR DESCRIPTION
**Pull request by mehtaRohit**
Added amazon link to the book "Practical C Programming by Steve Oualline".
The book is a great resource for beginners and for those wanting to start with C.
I think this book can be used with CS50 course.

### CODE REVIEW

**Comment by oNjEncUREn** [comment]
What makes that book better than _C Programming Language, Second Edition_ by Kernighan and Ritchie?  If we're going to include a book on C, I'd rather it be one from the language creator (Dennis Ritchie).

**Comment by mehtaRohit** [comment]
I have not read the _C Programming Language, Second Edition by Kernighan and Ritchie_, so I can not say. However, this book was quite easy to follow, understand and was quite clear on practical applications of everything it teaches about C.
I have no reason to say _Practical C Programming_ is better that one @oNjEncUREn  mentioned. But I can say that my first language was C and my introduction to CS was this book. As I found the book useful, I thouht it could help other students too.

**Comment by oNjEncUREn** [comment]
You bring up a valid point.  We all learned languages from different books.  Maybe we could look at splitting up the Readings so each language has its own section with a handful a books.

**Comment by mehtaRohit** [comment]
> You bring up a valid point. We all learned languages from different books. Maybe we could look at splitting up the Readings so each language has its own section with a handful a books.

That would be great!

**Review by lucalves — APPROVED** [review]

**Review by Uniminin — COMMENTED** [review]
bad commit message

**Comment by mehtaRohit** [comment]
@Uniminin Thanks for your opinion. Can you please elaborate how it is bad?

**Comment by Uniminin** [comment]
Still the commit message remains the same.

**Comment by mehtaRohit** [comment]
@Uniminin then I do not know what exactly you mean !

**Pull request closed without merging**
