### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aomine2023**
Removed Cybersecurity Fundamentals from curriculum

### CODE REVIEW

**Comment by aomine2023** [comment]
Closes #1055

**Comment by aayushsinha0706** [comment]
Please do see the contribution guidelines of the community and don't blindly create pull request. The issue RFC #1055 is there so that we can discuss replacement of CyberSecurity course.

**Comment by aomine2023** [comment]
Sorry will do,it is my first time contributing so I created one without much thought😅.

**Comment by aayushsinha0706** [comment]
Perfectly fine 😄 OSSU thrives from contributors. Do refer Contribution guidelines bedtime when you contribute. 
https://github.com/ossu/computer-science/blob/master/CONTRIBUTING.md

**Comment by aomine2023** [comment]
Sure ! Will do thanks a lot for helping out :D

**Pull request closed without merging**
