### PR TITLE
extras/courses: Add U of Helsinki OO Programming with Java

### PR DESCRIPTION
**Pull request by leungleoqin**
This is a widely regarded, text-based course on object-oriented programming/Java. I have taken it myself and found it very useful. This course has also allowed me to continue with other courses in the curriculum, such as the Princeton Algorithm course and From Nand to Tetris.

Here are a few more reasons for why this course should be added:

- Comprehensive coverage of the Java language (syllabi: [part 1](http://mooc.fi/courses/2013/programming-part-1/material.html), [part 2](http://mooc.fi/courses/2013/programming-part-2/material.html))
- Exercise-intensive (100+ small programming assignments) with easy-to-use auto-grader tool
- Text-based course which allows students to go at their own pace, without having to skip through videos to find the content they want

### CODE REVIEW

**Comment by waciumawanjohi** [comment]
I didn't realize mooc.fi wasn't included in our extras. Great resource, I endorse this!

**Comment by hanjiexi** [comment]
@leungleoqin Apologies for overlooking this. I'm having trouble finding reviews of this course. I just wanted to see what was said about it since you mentioned it's widely-regarded. Can you point me in the right direction?

> Exercise-intensive (100+ small programming assignments) with easy-to-use auto-grader tool

This is always a plus!

**Comment by waciumawanjohi** [comment]
http://sackofcrazy.com/mooc-review-object-oriented-programming-with-java-mooc-fi/
https://www.reddit.com/r/TheJavaBrewery/comments/2xp866/reviewonline_courseuniversity_of_helsinki_mooc/
[It's one of five resources recommended by /r/learnprogramming for learning Java.](https://www.reddit.com/r/TheJavaBrewery/comments/2xp866/reviewonline_courseuniversity_of_helsinki_mooc/)

**Comment by leungleoqin** [comment]
@hanjiexi It is definitely not as popular as courses like CS50/Stanford's Algorithms course, but when I was researching resources to learn Java, most people recommended this course. UCSD also has a [Java course](https://www.coursera.org/learn/object-oriented-java?authMode=login#pricing) on Coursera now, but you have to pay to get access to the assignments.

**Comment by hanjiexi** [comment]
Thanks!

**Pull request merged**
