### PR TITLE
Add a competitive programming book

### PR DESCRIPTION
**Pull request by iamjackslayer**
This book shows solving techniques for learners interested in programming puzzles.
https://cpbook.net/

### CODE REVIEW

**Comment by waciumawanjohi** [comment]
Hi @iamjackslayer 
Can you add some additional information justifying this change? You have pointed out what students can learn from this book. Other relevant questions are:
- What alternative books could be included?
- Why should OSSU recommend this book instead of the alternatives?

This could be your own analysis. Or you could point to an analysis that already compares books teaching how to solve programming puzzles.

**Comment by hematogender** [comment]
#584 has some info on competitive programming which may come in handy.

**Comment by pachecohjr** [comment]
There's a course on edX titled How to Win Coding Competitions: Secrets of Champions.  Has anyone taken it yet?

**Comment by iamjackslayer** [comment]
Thank you for the questions for justification. The book (CP3, latest edition) is rigorously studied/referenced every semester by students taking the [CS3233 - competitive programming course](https://www.comp.nus.edu.sg/~stevenha/cs3233.html) in the National University of Singapore. The author of the book, who is also a senior lecturer in the university regularly coaches ICPC teams in South East Asia. 
A good alternative is [Programming Challenges by Steven Skiena](https://www.amazon.com/Programming-Challenges-Contest-Training-Computer/dp/0387001638). A good comparison can be made in terms of the breadth. CP distilled [3000+ UVa plus Kattis](https://cpbook.net/methodstosolve) while Programming Challenges distilled 1000+ problems from Universidad de Valladolid online judge. 
My own takeaway is that CP is to a large extent more "rigorously tested" since it is an official textbook from a university class.

**Comment by waciumawanjohi** [comment]
On both Amazon and Goodreads this book is the top result for the search "Competitive Programming" with the most reviews and the highest review average.

**Pull request merged**
