### PR TITLE
Fix stale links

### PR DESCRIPTION
**Pull request by aaronhooper**
I checked all the links in the repo to see if any didn't return a HTTP 2xx or 3xx, and either updated or removed them.

### CODE REVIEW

**Comment by waciumawanjohi** [comment]
Good catch on both of these.
Regarding Compiler Construction, it looks like the author has made the book available on his personal faculty page here: https://inf.ethz.ch/personal/wirth/CompilerConstruction/index.html

If you update your pull request to include these pdfs for Compiler Construction, I'll merge this in.

Thanks!

**Comment by aaronhooper** [comment]
No worries, incoming

**Comment by waciumawanjohi** [comment]
Looks good. I'm going to merge this in. In the future, if there's a change needed to a pull request, after making a commit to fix the problem, you can do an interactive rebase to omit the problematic commit. (In this case, this would have led to just 2 commits `Update link to curricular guidelines` and `Update link for Compiler Construction`)

Here's an article that explains it better than I can:
https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history

**Comment by aaronhooper** [comment]
Aha, I had thought about squashing them, but I didn't since I wasn't sure if it was a good idea to rewrite public history in pull requests. Thanks for letting me know and I'll remember it in future!

**Pull request merged**
